version: "3.8"

services:
  app:
    image: josephrojas01/webpage_workshop
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
    #rango de variables
      - "3000-3001:3000"

  db:
    image: mongo:4.4.6
